name = "NoSleep"
uuid = "95f667b2-49e0-4955-80bd-390d74d178c7"
authors = ["Evgeny Metelkin <evgeny.metelkin@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.10, 1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
